spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.134:3306/subway?serverTimezone=UTC
    username: root
    password: masterpw
  jpa:
    hibernate:
      ddl-auto: validate
